### PR TITLE
Added support for hashed file names

### PR DESCRIPTION
**Pull request by vildehav**
Hash is added to all files that includes '[hash]'. Example: bundle.[hash].js

A caveat is that only one hash is used. So a change to stylesheet will generate a new hash for the javascript file also.

Disclaimer: I have only done basic testing with my own webpack configurations (basically with hash and without hash)

Webpack config example with hash included:

```
  output: {
    path: path.join(__dirname, 'public'),
    filename: './app.[hash].js',
    libraryTarget: 'umd',
    publicPath: '/',
  },

  plugins: [
    new ExtractTextPlugin('./app.[hash].css', { allChunks: true }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production'),
      },
    }),
    new webpack.optimize.UglifyJsPlugin({
      screw_ie8: true,
      compressor: { warnings: false },
    }),
    new StaticSitePlugin({
      src: 'app',
      bundle: '/app.[hash].js',
      stylesheet: '/app.[hash].css',
      favicon: '/favicon.ico',
    }),
  ],
```

### CODE REVIEW

**Comment by iansinnott** [comment]
Hey @vildehav, sorry I didn't see this earlier. Hash support would be great. I just pushed a large update to the plugin that changed a lot, if you're still interested I'd love to get this merged in.

**Comment by glennreyes** [comment]
Cool would be also interested about that! How would you refer to the the hashed file in the template?

**Comment by iansinnott** [comment]
I think even after the 1.0 update we could still pass it in through the plugin
options as this PR shows in the example. Open to suggestion sthough.

On Jul 12 2016, at 8:16 am, Glenn Reyes &lt;notifications@github.com&gt;
wrote:  

> Cool would be also interested about that! How would you refer to the the
hashed file in the template?

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on
GitHub](https://github.com/iansinnott/react-static-webpack-
plugin/pull/6#issuecomment-232080597), or [mute the
thread](https://github.com/notifications/unsubscribe
/ADAjsXA0ndL8GeLtvP2eolE7K-
NEf9bNks5qU6_PgaJpZM4IvtcC).

**Comment by vildehav** [comment]
Took a stab at it. 

The filenames needs to be explicitly set in the plugins option object and then referenced in the template.js file via props.

Any name can be used for the filenames, if it contains a [hash] string it will be replaced with the correct hash. 

NOTE: Does not support [name] parameter in the filename

Example webpack config:

 ```
   new ReactStaticPlugin({
      routes: './client/routes.js',
      template: './template.js',
      bundle: 'app.[hash].js',
      stylesheet: 'app.[hash].css',
    })

```

Example template.js:

```
const Html = (props) => (
  <html lang='en'>
    <head>
      <meta charSet='utf-8' />
      <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
      <meta name='viewport' content='width=device-width, minimum-scale=1.0' />
      <link rel='stylesheet' href={props.stylesheet} />
      <title>{props.title}</title>
    </head>
    <body>
      <div id='root' dangerouslySetInnerHTML={{ __html: props.body }} />
      <script src={props.bundle} />
    </body>
  </html>
);
```

**Comment by glennreyes** [comment]
Thank you @vildehav! Is there a way to access to multiple bundles? Like when you have multiple entrypoints defined in your webpack configuration?

**Comment by vildehav** [comment]
@glennreyes not sure about how it would work for different js files for say about.html and home.html etc. 
But if you want an app bundle and a vendor bundle you would do this. A caveat here is that they would get the same hash so both would be cache invalidated at the same time even if you only changed the appBundle.

```
 new ReactStaticPlugin({
      routes: './client/routes.js',
      template: './template.js',
      appBundle: 'app.[hash].js',
      vendorBundle: 'vendor.[hash].js',
    })

```
and then in the template

```
<script src={props.vendorBundle} />
<script src={props.appBundle} />
```



Off the top of my head, one way to to get html specifik bundles might be to do something like this in the template: 

`<script src={props.title === 'home' ? props.homeBundle : props.notHomeBundle} />`

But it feels a bit frail, @iansinnott probably has a better solution for this scenario.

**Comment by iansinnott** [comment]
I have yet to use this option myself so I'm not too sure what the ideal API would look like. We might consider just passing the hash to the template directly and the user can do whatever they want with it.

**Comment by vildehav** [comment]
Yeah that would be a way to go, just have the hash as a prop. An do like this in the template: 

` <script src={`app.${props.hash}.js`} />`

My specifik use case at the moment is more suited for the all in config solution. I use "absolute" names (like '/content/core.[hash].js' etc) so it is easier to just have to change it in one file. And the template stays the same. 

That said i guess this would work as well in the template and might be a cleaner implementation:

` <script src={addHash(props.bundle, props.hash)} /> `

**Comment by iansinnott** [comment]
I would tend to favor the `props.hash` option because it's simpler. Meaning the user doesn't have to know that they can provide `app.[hash].js` in the template, the just have to know that they have access to the compilation hash within their templates.

But that being said, @vildehav since you made the PR you're the voice of authority on what makes this feature useful, so if your needs are currently being met then I'm happy to keep it the way it is 👍

**Comment by vildehav** [comment]
@iansinnott  sry for late respons, been on vacation.

Well this works for me, so if you are ok with it we can leave it as is for the time being.

**Comment by iansinnott** [comment]
Sounds good @vildehav 👍 . We can always bump major version if this functionality changes to pass the hash instead of replacing `[hash]` within strings.

**Pull request merged**
