### PR TITLE
use createRoutes from ReactRouter

### PR DESCRIPTION
**Pull request by marcgreenstock**
I thought I would take a stab at using `createRoutes` instead of iterating through the child components.

The previous implementation didn't work when child routes are built as using a `PlainRoute`.

### CODE REVIEW

**Comment by iansinnott** [comment]
Nice, it would be great to have a universal solution that always worked with React Router. I've never used `PlainRoute`. I'm sure we could make it work with the existing codebase but using a built in RR method would be preferable. 

If you fix the breaking build issues and all tests are passing then i'm happy to merge this in.

**Comment by iansinnott** [comment]
I update the readme to (hopefully) make it more clear how to run the tests locally. Basically, from the project root you can run:

```
./install_test_dependencies.sh
```

```
npm test
```

**Comment by marcgreenstock** [comment]
Hi @iansinnott `PlainRoute` is a simple JS object that describes the routes. ReactRouter allows you to write routes as a component and as a `PlainRoute`, combining them is also permitted.

My solution may not work for `PlainRoute` only routes because of the `RouteShape` defined in `utils.js`. I've never used Flow so I'm not really up on the syntax to make it work with type checking. Without the Flow type checking it *should* work universally for any type of ReactRouter routes export. As long as `createRoutes` can pass it, the paths can be extracted.

I'll fix the specs as you suggest.

**Comment by iansinnott** [comment]
Cool, thanks. I'm happy to add in the type signatures myself, but they will keep the tests from passing so if you get failing flow checks but your own testing works fine then just let me know and I can go in and update the flow types.

Also, I noticed that I have some failing tests right now through not fault of yours, so I need to get the tests back in order before merging this so no rush.

**Pull request closed without merging**
